### ISSUE TITLE
Compilation Fail on verilator tb @ ffde2e9

### ISSUE THREAD

**Issue by papantonisp** [openhwgroup/cv-hpdcache#54]
I am trying to run the verilator tb at commit: ffde2e9

I have installed systemc and scv. Also I have export the env vars below
`export SYSTEMC_HOME=/home/pap/Projects/systemc-3.0.1  `
`export SCV_HOME=/home/pap/Projects/scv-2.0.1`
`export SYSTEMC_LIBDIR=$SYSTEMC_HOME/lib-linux64`
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SYSTEMC_HOME/lib-linux64`
When I tried to run the verilator tb by command  
`make build -j8`
 I got and an compilation error related to the scv.h file. 
 I edited the Makefile and I added the SCV_HOME/src as INCDIR
`USER_CPPFLAGS       +=  I$(SCV_HOME)/src`
This edit helped to bypass this issue and the compilation completed.
Although during the linking phase I get the errors below

```
g++   -Wl,-rpath,/home/pap/Projects/systemc-3.0.1/lib-linux64   -L/home/pap/Projects/systemc-3.0.1/lib-linux64 hpdcache_tb.o verilated.o verilated_vcd_c.o verilated_threads.o Vhpdcache_wrapper__ALL.a  -lscv  -pthread -lpthread -latomic  -lsystemc -o Vhpdcache_wrapper
/usr/bin/ld: hpdcache_tb.o: warning: relocation against `_ZN7sc_core8sc_event4noneE' in read-only section `.text._ZNK7sc_core17sc_event_finder_tINS_15sc_signal_in_ifIbEEE10find_eventEPNS_12sc_interfaceE[_ZNK7sc_core17sc_event_finder_tINS_15sc_signal_in_ifIbEEE10find_eventEPNS_12sc_interfaceE]'
/usr/bin/ld: verilated.o: in function `_GLOBAL__sub_I__ZN9Verilated7s_debugE':
verilated.cpp:(.text.startup+0x1d): undefined reference to `sc_core::sc_api_version_2_3_4_cxx201703L<&sc_core::SC_DISABLE_VIRTUAL_BIND_UNDEFINED_>::sc_api_version_2_3_4_cxx201703L(sc_core::sc_writer_policy, bool)'
/usr/bin/ld: verilated_vcd_c.o: in function `_GLOBAL__sub_I__ZN14VerilatedTraceI12VerilatedVcd18VerilatedVcdBufferE16getOffloadBufferEv':
verilated_vcd_c.cpp:(.text.startup+0xc): undefined reference to `sc_core::sc_api_version_2_3_4_cxx201703L<&sc_core::SC_DISABLE_VIRTUAL_BIND_UNDEFINED_>::sc_api_version_2_3_4_cxx201703L(sc_core::sc_writer_policy, bool)'
...
/usr/bin/ld: Vhpdcache_wrapper__ALL.a(Vhpdcache_wrapper__Trace__1.o): in function `_GLOBAL__sub_I__Z42Vhpdcache_wrapper___024root__trace_cleanupPvP12VerilatedVcd':
Vhpdcache_wrapper__Trace__1.cpp:(.text.startup+0xc): undefined reference to `sc_core::sc_api_version_2_3_4_cxx201703L<&sc_core::SC_DISABLE_VIRTUAL_BIND_UNDEFINED_>::sc_api_version_2_3_4_cxx201703L(sc_core::sc_writer_policy, bool)'
/usr/bin/ld: Vhpdcache_wrapper__ALL.a(Vhpdcache_wrapper__ConstPool_0.o): in function `_GLOBAL__sub_I_Vhpdcache_wrapper__ConstPool__CONST_h55f3f2b8_0':
Vhpdcache_wrapper__ConstPool_0.cpp:(.text.startup+0xc): undefined reference to `sc_core::sc_api_version_2_3_4_cxx201703L<&sc_core::SC_DISABLE_VIRTUAL_BIND_UNDEFINED_>::sc_api_version_2_3_4_cxx201703L(sc_core::sc_writer_policy, bool)'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[1]: *** [Vhpdcache_wrapper.mk:66: Vhpdcache_wrapper] Error 1
``` 

Under the $SYSTEMC_HOME/lib-linux64 I have the libs below

- libscv-2.0.1.so
- libscv.a
- libscv.la
- libscv.so -> libscv-2.0.1.so
- libsystemc-3.0.0.so
- libsystemc.a
- libsystemc.la
- libsystemc.so -> libsystemc-3.0.0.so

Any idea what is wrong on my setup?

**Comment by cfuguet** [comment]
Hello,

It looks like an incompatibility between Verilator and SystemC.

Did you first compile SystemC and SCV then Verilator ? I've always compiled in that order and with the same compiler. Otherwise, I've remember to have that kind of issue.

In the .github subdirectory you can find the scripts to install the whole thing:

1. https://github.com/openhwgroup/cv-hpdcache/blob/master/.github/scripts/env.sh
2. https://github.com/openhwgroup/cv-hpdcache/blob/master/.github/scripts/install_systemc.sh
3. https://github.com/openhwgroup/cv-hpdcache/blob/master/.github/scripts/install_verilator.sh

You need to run them in that order.

If you are in Ubuntu/Debian, there is also the https://github.com/openhwgroup/cv-hpdcache/blob/master/.github/scripts/install_deps_ubuntu.sh, which installs the required dependencies (to be run before the scripts above).

**Comment by papantonisp** [comment]
It  worked!! Thx for the quick response.
